# Configuraci칩n del puerto.
server:
  port: 8081
  
# Configuraci칩n de consola
logging:
  pattern:
    dateformat: hh:mm:ss
  level:
    org:
      hibernate: 
        SQL: DEBUG
      type:
          descriptor:
            sql: 
              BasicBinder: TRACE
              
# Configuraciones de Spring.
spring:
  main:
    banner-mode: off # Quita el banner de Spring al ejecutar la consola

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    
    # Configuraci칩n para mostrar el SQL que se est치 ejecutando
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
      format_sql: true

  # Base de Datos
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
